[package]
name = "crustyArch"
version = "0.1.0"
edition = "2024"

[lib]
name = "crustyArch"
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.28.0"
# NOTE: Check cbindgen version first with 'cbindgen --version' and enter that version here.
