[build]
target = "thumbv7em-none-eabi"
 
[target.thumbv7em-none-eabi]
rustflags = [
  "-C", "target-cpu=cortex-m4",
  "-C", "target-feature=+vfp4",
  "-C", "codegen-units=1",
  "-C", "lto=off",
  "-C", "debuginfo=1",
]
